//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mrSampleShaders.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_SHADERLIST_PARAMS           3
#define IDS_FRONT                       3
#define IDS_PARAMS                      4
#define IDS_MATERIAL_SHADERS            4
#define IDS_SHADERS_ON                  4
#define IDS_BACK                        4
#define IDS_SPIN                        5
#define IDS_OPAQUE                      5
#define IDS_SHADERS                     5
#define IDS_TWOSIDEDSHADER_CLASSNAME    5
#define IDS_SURFACE                     6
#define IDS_NONE                        6
#define IDS_PARAMETERS                  6
#define IDS_MTL1                        7
#define IDS_LENS                        7
#define IDS_TWOSIDEDSHADER_PARAMETERS   7
#define IDS_MTL1ON                      8
#define IDS_DISPLACEMENT                8
#define IDS_FRONTCOLOR                  8
#define IDS_SHADOW                      9
#define IDS_BACKCOLOR                   9
#define IDS_PHOTON                      10
#define IDS_OUTPUT                      10
#define IDS_FRONTMAP                    10
#define IDS_PHOTONVOL                   11
#define IDS_PHOTONVOLUME                11
#define IDS_BACKMAP                     11
#define IDS_ENVIRONMENT                 12
#define IDS_FRONTMAPON                  12
#define IDS_CONTOUR                     13
#define IDS_BUMP                        13
#define IDS_BACKMAPON                   13
#define IDS_LIGHTMAP                    14
#define IDS_CURRENTSHADER               14
#define IDS_MATERIAL_PARAMETERS         15
#define IDS_ADVANCED_SHADERS            15
#define IDS_SELECTED                    15
#define IDS_VOLUME                      16
#define IDS_SURFACE_ON                  17
#define IDS_BUMP_ON                     18
#define IDS_DISPLACE_ON                 19
#define IDS_SHADOW_ON                   20
#define IDS_PHOTON_ON                   21
#define IDS_PHOTONVOL_ON                22
#define IDS_ENVIRONMENT_ON              23
#define IDS_CONTOUR_ON                  24
#define IDS_LIGHTMAP_ON                 25
#define IDS_VOLUME_ON                   26
#define IDD_PANEL                       101
#define IDS_TEXTURE                     102
#define IDS_SHADERLIST_CLASSNAME        103
#define IDD_MRMATERIAL                  149
#define IDD_SHADERLIST                  149
#define IDD_TWOSIDEDSHADER              149
#define IDS_STRING104                   150
#define IDB_MATICONS                    173
#define IDB_MATICONS_MASK               174
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_CHECK_CONTOUR               1001
#define IDC_CHECK_LIGHTMAP              1002
#define IDC_CHECK_PHOTON                1003
#define IDC_BUTTON_MTLshader            1004
#define IDC_BUTTON_CONTOUR              1004
#define IDC_CHECK_MTLopaque             1005
#define IDC_BUTTON_MTLdisplacement      1006
#define IDC_BUTTON_MTLshadow            1007
#define IDC_BUTTON_MTLvolume            1008
#define IDC_BUTTON_MTLenvironment       1009
#define IDC_BUTTON_MTLcontour           1010
#define IDC_BUTTON_MTLphoton            1011
#define IDC_BUTTON_MTLphotonVolume      1012
#define IDC_BUTTON_MTLlightMap          1013
#define IDC_BUTTON_MTLbump              1014
#define IDC_BUTTON_LIGHTMAP             1015
#define IDC_BUTTON_PHOTON               1016
#define IDC_BUTTON_PHOTONVOL            1017
#define IDC_CHECK_PHOTONVOL             1018
#define IDC_BUTTON_BUMP                 1019
#define IDC_CHECK_BUMP                  1020
#define IDC_SHADER_ON                   1020
#define IDC_BUTTON_DISPLACEMENT         1021
#define IDC_CHECK_DISPLACEMENT          1022
#define IDC_BUTTON_VOLUME               1023
#define IDC_CHECK_VOLUME                1024
#define IDC_BUTTON_ENVIRONMENT          1025
#define IDC_CHECK_ENVIRONMENT           1026
#define IDC_CHECK_OPAQUE                1027
#define IDC_CHECK_SURFACE               1028
#define IDC_BUTTON_SURFACE              1029
#define IDC_BUTTON_SHADER               1029
#define IDC_BUTTON_FRONTMAP             1029
#define IDC_CHECK_SHADOW                1030
#define IDC_BUTTON_SHADOW               1031
#define IDC_COLOR_FRONT                 1031
#define IDC_LIST1                       1032
#define IDC_BUTTON1                     1033
#define IDC_BUTTON_ADD                  1033
#define IDC_BUTTON_BACKMAP              1033
#define IDC_BUTTON2                     1034
#define IDC_BUTTON_REMOVE               1034
#define IDC_COLOR_BACK                  1034
#define IDC_BUTTON_UP                   1035
#define IDC_BUTTON_DOWN                 1036
#define IDC_CHECK_FRONTMAPON            1038
#define IDC_CHECK_BACKMAPON             1039
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_MTL1                        1497
#define IDC_LIST_SHADERS                1497
#define IDC_MTLON1                      1498

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
